---
- hosts: all
  become: true
  roles:
    - role: system
      tags:
        - system

    - name: Jellyfin podman container
      role: podman_systemd_container
      vars:
        container_name: jellyfin
        container_image: docker.io/jellyfin/jellyfin:latest
        published_ports:
          - 8096:8096
        group_add:
          - "{{ render_group }}"
        devices:
          - /dev/dri/renderD128:/dev/dri/renderD128
        volumes:
          - "{{ storage_dir }}/jellyfin/cache:/cache"
          - "{{ storage_dir }}/jellyfin/config:/config"
        shared_volumes:
          - "{{ storage_dir }}/media:/media"
        env:
          TZ: "{{ timezone }}"
          PUID: "{{ uid }}"
          PGID: "{{ gid }}"
        network: mediarr
        network_aliases:
          - jellyfin
      tags:
        - jellyfin
        - podman

    - name: Qbittorrent podman container
      role: podman_systemd_container
      vars:
        container_name: qbittorrent
        container_image: lscr.io/linuxserver/qbittorrent:latest
        published_ports:
          - 8080:8080
          - 6881:6881
        volumes:
          - "{{ storage_dir }}/mediarr/qbittorrent:/config"
        shared_volumes:
          - "{{ storage_dir }}/media:/mnt/media"
          - "{{ storage_dir }}/downloads:/mnt/downloads"
        env:
          TZ: "{{ timezone }}"
          PUID: "{{ uid }}"
          PGID: "{{ gid }}"
          WEBUI_PORT: 8080
        network: mediarr
        network_aliases:
          - qbittorrent
      tags:
        - qbittorrent
        - podman

    - name: Jellyseer podman container
      role: podman_systemd_container
      vars:
        container_name: jellyseer
        container_image: fallenbagel/jellyseerr:latest
        published_ports:
          - 5055:5055
        volumes:
          - "{{ storage_dir }}/mediarr/jellyseer:/app/config"
        env:
          TZ: "{{ timezone }}"
        network: mediarr
        network_aliases:
          - jellyseer
      tags:
        - jellyseer
        - podman

    - name: Bazaar podman container
      role: podman_systemd_container
      vars:
        container_name: bazaar
        container_image: lscr.io/linuxserver/bazarr:latest
        published_ports:
          - 6767:6767
        volumes:
          - "{{ storage_dir }}/mediarr/bazaar:/config"
        shared_volumes:
          - "{{ storage_dir }}/media:/mnt/media"
        env:
          TZ: "{{ timezone }}"
          PUID: "{{ uid }}"
          PGID: "{{ gid }}"
        network: mediarr
        network_aliases:
          - bazarr
      tags:
        - bazaar
        - podman

    - name: Prowlarr podman container
      role: podman_systemd_container
      vars:
        container_name: prowlarr
        container_image: lscr.io/linuxserver/prowlarr:latest
        published_ports:
          - 9696:9696
        volumes:
          - "{{ storage_dir }}/mediarr/prowlarr:/config"
        env:
          TZ: "{{ timezone }}"
          PUID: "{{ uid }}"
          PGID: "{{ gid }}"
        network: mediarr
        network_aliases:
          - prowlarr
      tags:
        - prowlarr
        - podman

    - name: Flaresolverr podman container
      role: podman_systemd_container
      vars:
        container_name: flaresolverr
        container_image: ghcr.io/flaresolverr/flaresolverr:latest
        env:
          TZ: "{{ timezone }}"
        network: mediarr
        network_aliases:
          - flaresolverr
      tags:
        - flaresolverr
        - podman

    - name: Radarr podman container
      role: podman_systemd_container
      vars:
        container_name: radarr
        container_image: lscr.io/linuxserver/radarr:latest
        published_ports:
          - 7878:7878
        volumes:
          - "{{ storage_dir }}/mediarr/radarr:/config"
        shared_volumes:
          - "{{ storage_dir }}/media:/mnt/media"
          - "{{ storage_dir }}/downloads:/mnt/downloads"
        env:
          TZ: "{{ timezone }}"
          PUID: "{{ uid }}"
          PGID: "{{ gid }}"
        network: mediarr
        network_aliases:
          - radarr
      tags:
        - radarr
        - podman

    - name: Readarr podman container
      role: podman_systemd_container
      vars:
        container_name: readarr
        container_image: lscr.io/linuxserver/readarr:develop
        published_ports:
          - 8787:8787
        volumes:
          - "{{ storage_dir }}/mediarr/readarr:/config"
        shared_volumes:
          - "{{ storage_dir }}/media:/mnt/media"
          - "{{ storage_dir }}/downloads:/mnt/downloads"
        env:
          TZ: "{{ timezone }}"
          PUID: "{{ uid }}"
          PGID: "{{ gid }}"
        network: mediarr
        network_aliases:
          - readarr
      tags:
        - readarr
        - podman

    - name: Sonarr podman container
      role: podman_systemd_container
      vars:
        container_name: sonarr
        container_image: lscr.io/linuxserver/sonarr:latest
        published_ports:
          - 8989:8989
        volumes:
          - "{{ storage_dir }}/mediarr/sonarr:/config"
        shared_volumes:
          - "{{ storage_dir }}/media:/mnt/media"
          - "{{ storage_dir }}/downloads:/mnt/downloads"
        env:
          TZ: "{{ timezone }}"
          PUID: "{{ uid }}"
          PGID: "{{ gid }}"
        network: mediarr
        network_aliases:
          - sonarr
      tags:
        - sonarr
        - podman

    - name: Homearr podman container
      role: podman_systemd_container
      vars:
        container_name: homearr
        container_image: ghcr.io/ajnart/homarr:latest
        published_ports:
          - 7575:7575
        volumes:
          - "{{ storage_dir }}/mediarr/homearr/configs:/app/data/configs"
          - "{{ storage_dir }}/mediarr/homearr/icons:/app/public/icons"
          - "{{ storage_dir }}/mediarr/homearr/data:/data"
        network: mediarr
        network_aliases:
          - homearr
      tags:
        - homearr
        - podman

    - name: Copyparty config
      role: copyparty_config
      vars:
        copyparty_config_dir: "{{ storage_dir }}/copyparty/config"
      tags:
        - copyparty

    - name: Copyparty podman container
      role: podman_systemd_container
      vars:
        container_name: copyparty
        container_image: copyparty/ac:latest
        published_ports:
          - 3923:3923
        volumes:
          - "{{ storage_dir }}:/w"
          - "{{ storage_dir }}/copyparty/config:/cfg"
      tags:
        - copyparty
        - podman
