- name: Create network-wait user systemd unit
  become: false
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user }}/.config/systemd/user/network-wait.service"
    content: |
      [Unit]
      Description=Wait for network to be online via NetworkManager or Systemd-Networkd

      [Service]
      Type=oneshot
      ExecStart=/bin/bash -c ' \
          if command -v nm-online &>/dev/null; then \
              nm-online -s -q; \
          elif command -v /usr/lib/systemd/systemd-networkd-wait-online &>/dev/null; then \
              /usr/lib/systemd/systemd-networkd-wait-online; \
          else \
              echo "Error: Neither nm-online nor systemd-networkd-wait-online found."; \
              exit 1; \
          fi'
      ExecStartPost=ip -br addr
      RemainAfterExit=yes
      Environment=NM_ONLINE_TIMEOUT=60

      [Install]
      WantedBy=default.target
    mode: "644"

- name: Start network-wait systemd unit for user
  become: false
  ansible.builtin.systemd:
    name: network-wait.service
    scope: user
    enabled: true
    daemon_reload: true
