---
- name: Create copyparty config directory
  ansible.builtin.file:
    path: "{{ copyparty_config_dir }}"
    recurse: true
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy copyparty config
  ansible.builtin.template:
    src: "config.j2"
    dest: "{{ copyparty_config_dir }}/config.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
